### ISSUE TITLE
Suggestion to add a subtraction of a median filtered image to background subtraction notebooks

### ISSUE THREAD

**Issue by biovoxxel** [BiAPoL/PoL-BioImage-Analysis-TS-Early-Career-Track#13]
@zoccoler 

- original 
- median filtered version
- original - median filtered image

This is the same as the gaussian subtraction, but way more effective. It is minimally as good as the top hat,
I will explain that in the theory part together with the TopHat. 
So, it might be good to have in the notebooks as well.

**Comment by biovoxxel** [comment]
Edit: This however only makes sense for small structures (spots or filaments). In the zebrafish eye, the nuclei might be too big

**Comment by zoccoler** [comment]
Alright, could you check in the 'data' folder of this repo if there is an image suitable for that? Or if you have another good example that can be used, just put it in the folder
I can then add this operation to the notebook :)

**Comment by biovoxxel** [comment]
I added the image `C2C12-Nuclei.tif` as good example

**Comment by zoccoler** [comment]
Thanks, I will update the notebook and then close this.
