### ISSUE TITLE
Add surface materials

### ISSUE THREAD

**Issue by jo-mueller** [BiAPoL/PoL-BioImage-Analysis-TS-Early-Career-Track#15]
@marcomusy I'll just create this issue to keep track on what's left to be added to the repo and what's already there.

I already added some basic materials in PR #14, which should also show what needs to be changed in the [toc.yaml](https://github.com/BiAPoL/PoL-BioImage-Analysis-TS-Early-Career-Track/blob/main/docs/_toc.yml) :)

- [x] marching cubes notebook
- [x] [Basics notebook ](https://github.com/LauAvinyo/vedo-embo-course/blob/main/solutions/01-basics.ipynb) on meshes
- [x] [Genes on meshes](https://github.com/LauAvinyo/vedo-embo-course/blob/main/solutions/05-gene_mesh.ipynb)
- [x] [Interpolate on mesh](https://github.com/LauAvinyo/vedo-embo-course/blob/main/solutions/06-interpolate_scalar.ipynb)
- [x] [Warp mesh](https://github.com/LauAvinyo/vedo-embo-course/blob/main/solutions/08-warp_mesh.ipynb)

**Comment by marcomusy** [comment]
Just submitted a PR!
