### ISSUE TITLE
Crop content of Python crash course 

### ISSUE THREAD

**Issue by jo-mueller** [BiAPoL/PoL-BioImage-Analysis-TS-Early-Career-Track#4]
We have 1.5h time - the materials should fit in there.

Topics we should/cover: (from @thawn 's course in Paris)

- Variable assignment
- Working with strings & comments
- Lists 
- For loops
- If conditions
- Functions: 
  - Make `Documentation` and `Simplification` subheaders of custom functions
  - Add method functions (`class.method()`) as function call example to functions notebook

- [x] modify functions notebook (@jo-mueller)
- [x] grade notebooks in **must do** and **optional** as well as give entry points to different programming levels (@jo-mueller)
- [x] Split presentation in two parts and link in Readme (@thawn )

**Comment by thawn** [comment]
@jo-mueller
* [ ] there are still two PDF slide sets in your session, but there is only one ppt file in the owncloud folder. Is that correct?
* [x] There still are a lot of notebooks. As far as I remember, we agreed to delete the ones that are marked as optional (and link to the bioimage analysis notebooks instead

My part is done.

**Comment by jo-mueller** [comment]
Hi @thawn ,

I originally just added a comment in the readme that pointed at the notebooks of interest, but I've now removed the others entirely and added a `See also` section in the respective readme. As for the slides - maybe something didn't sync properly? I see two pdfs in the repo and also two ppt in the teaching materials on cloudstore.

**Comment by thawn** [comment]
I see the following files in the repo:
![image](https://github.com/BiAPoL/PoL-BioImage-Analysis-TS-Early-Career-Track/assets/1308449/b9b692e2-054d-459a-83f4-492665a112c7)
and I see the following files in the cloud:
<img width="210" alt="image" src="https://github.com/BiAPoL/PoL-BioImage-Analysis-TS-Early-Career-Track/assets/1308449/16c8b37e-240c-45ff-b2fb-d59b74b56f8e">

can you please make sure that python_basics.pdf (currently 13 pages) matches the slides (10_python_basics.ppt) you are going to show (currently 31 slides)? And that you really need python_data_structures.pdf.

I have also found some obsolete slides and a movie in my folder. I have removed those in pull request #28 . Maybe, you could merge that one, once you are sure that the pdfs in your python basics session are correct.

Cheers,

Till

**Comment by thawn** [comment]
Also, we should make sure that the dates and authors on the ppt slides and the pdfs are correct

**Comment by jo-mueller** [comment]
@thawn ah, I see. Thanks for spotting it! I removed the old data_structures.pdf and updated the pdf in the repo.
